eureka:
  client:
    service-url:
      defaultZone: http://localhost:9901/eureka/
spring:
  application:
    name: service-zuul
# 路由规则配置
zuul:
  routes:
    api-service-x:
      path: /xServiceByFeign/**
      serviceId: service-x
